<a href="https://colab.research.google.com/github/Jflorez05/Especializacion-Analitica/blob/main/Prueba_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Prueba #2**
En la siguiente pureba se evalua de manera EXCLUSIVA lo que se solicita, cualquier otra respuesta adicional a ella será valorada, más no evaluada. Entregue la prueba en un repositorio de github antes de el domingo 18 de Febrero a las 23:59:59.

## **Ejercicio 1** (40%)

Construya un DataFrame a partir del siguiente diccionario

`exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, 10, 9, 20, 14.5, 12, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1], 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}`

con las siguientes etiquetas para los índices

`labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']`

1. Seleccione solo las columnas *name* y *score*.
  
2. Filtre las filas donde el número de intentos (attemps) sea mayor que 2.

3. Filtre las filas donde el *score* se encuentre entre 15 y 20 (incluidos)

4. Cambie el *score* en la fila 'd' a 11.5

5. Agregue una nueva fila con etiqueta 'k' al dataframe con un valor que usted desee para cada columna

6. Borre la fila 'k' y entregue nuevamente el DataFrame original.

7. Ordene el DataFrame por nombre en orden ascendente.

8. Reemplace los valores de la columna *qualify* que contiene los valores *yes* y *no* por los valores booleanos True y False respectivamente.

## **Ejercicio 2** (30%)

Importe el dataset `athletes` del repositorio del curso y realice las siguientes tareas:

1. Importarlo como nombre athletes

In [1]:
import pandas as pd
import numpy as np

athletes = pd.read_csv('https://raw.githubusercontent.com/tomasate/Datos_Clases/main/Datos_1/athletes.csv')
athletes.head()

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze
0,736041664,A Jesus Garcia,ESP,male,10/17/69,1.72,64.0,athletics,0,0,0
1,532037425,A Lam Shin,KOR,female,9/23/86,1.68,56.0,fencing,0,0,0
2,435962603,Aaron Brown,CAN,male,5/27/92,1.98,79.0,athletics,0,0,1
3,521041435,Aaron Cook,MDA,male,1/2/91,1.83,80.0,taekwondo,0,0,0
4,33922579,Aaron Gate,NZL,male,11/26/90,1.81,71.0,cycling,0,0,0

2. Filtre el dataframe tal que solo se quede con los atletas que hayan ganado al menos una medalla.

In [2]:
# Filtrado del dataset con unicamente los atletas que han ganado al menos una medalla.
athletes_medal = athletes.loc[(athletes.gold > 0) | (athletes.silver > 0) | (athletes.bronze > 0) ]
athletes_medal

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze
2,435962603,Aaron Brown,CAN,male,5/27/92,1.98,79.0,athletics,0,0,1
6,266237702,Aaron Russell,USA,male,6/4/93,2.05,98.0,volleyball,0,0,1
14,162792594,Abbey Weitzeil,USA,female,12/3/96,1.78,68.0,aquatics,1,1,0
48,962468808,Abdoulrazak Issoufou Alfaga,NIG,male,12/26/94,2.07,98.0,taekwondo,0,1,0
55,969824503,Abdullah Alrashidi,IOA,male,8/21/63,1.83,84.0,shooting,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
11487,334126873,Zhiyong Shi,CHN,male,10/10/93,1.68,69.0,weightlifting,1,0,0
11491,105609876,Zi He,CHN,female,12/10/90,1.60,52.0,aquatics,0,1,0
11503,593183472,Zivko Gocic,SRB,male,8/22/82,1.93,93.0,aquatics,1,0,0
11509,836633838,Zoe Lee,GBR,female,12/15/85,1.76,70.0,rowing,0,1,0
11511,343671816,Zoe de Toledo,GBR,female,7/17/87,1.72,58.0,rowing,0,1,0

3. Calcule la masa muscular por fila con una función como

$$I_{m.m.} = \frac{Weight}{Height^2}$$

In [3]:
# Cálculo del indice de masa por fila con una función

def mass_index(row, weight, height):

    """
    Calculates the Body Mass Index (BMI) for a specific row of a DataFrame.

    Parameters:
        - row: A specific row of the DataFrame.
        - weight: The name of the column containing athletes' weights.
        - height: The name of the column containing athletes' heights.

    Returns:
        The calculated Body Mass Index (BMI) for the given row.
    """
    return row[weight]/((row[height])**2)

# Aplica la función mass_index a cada fila de athletes_medal y almacena el resultado en una nueva columna llamada 'mass_index'
athletes_medal['mass_index'] =athletes_medal.apply(mass_index,
                                        axis = 1,
                                        args = [ 'weight', 'height'])

athletes_medal

<ipython-input-3-ee7135459c57>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  athletes_medal['mass_index'] =athletes_medal.apply(mass_index,

,id,name,nationality,sex,dob,height,weight,sport,gold,silver,bronze,mass_index
2,435962603,Aaron Brown,CAN,male,5/27/92,1.98,79.0,athletics,0,0,1,20.151005
6,266237702,Aaron Russell,USA,male,6/4/93,2.05,98.0,volleyball,0,0,1,23.319453
14,162792594,Abbey Weitzeil,USA,female,12/3/96,1.78,68.0,aquatics,1,1,0,21.461937
48,962468808,Abdoulrazak Issoufou Alfaga,NIG,male,12/26/94,2.07,98.0,taekwondo,0,1,0,22.871012
55,969824503,Abdullah Alrashidi,IOA,male,8/21/63,1.83,84.0,shooting,0,0,1,25.082863
...,...,...,...,...,...,...,...,...,...,...,...,...
11487,334126873,Zhiyong Shi,CHN,male,10/10/93,1.68,69.0,weightlifting,1,0,0,24.447279
11491,105609876,Zi He,CHN,female,12/10/90,1.60,52.0,aquatics,0,1,0,20.312500
11503,593183472,Zivko Gocic,SRB,male,8/22/82,1.93,93.0,aquatics,1,0,0,24.967113
11509,836633838,Zoe Lee,GBR,female,12/15/85,1.76,70.0,rowing,0,1,0,22.598140
11511,343671816,Zoe de Toledo,GBR,female,7/17/87,1.72,58.0,rowing,0,1,0,19.605192

4. Agrupe los datos por calculando la media por deporte para cada una del resto de características. ¿Cuál es el deporte en el que los jugadores tienen mayor peso promedio?

**Respuesta 2.4:** El deporte que tiene el mayor peso promedio es el **Basketball.**

In [5]:
# Agrupación de los datos calculando la media de las carécteristicas por deporte y seleccionar deporte con mayor peso promedio
athletes_medal.groupby('sport').mean().sort_values('weight',ascending= False)

<ipython-input-5-28431b319aca>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  athletes_medal.groupby('sport').mean().sort_values('weight',ascending= False)

,id,height,weight,gold,silver,bronze,mass_index
sport,,,,,,,
basketball,4.855873e+08,1.929861,87.527778,0.333333,0.333333,0.333333,23.264874
handball,4.694044e+08,1.850000,86.027027,0.329545,0.340909,0.329545,24.399223
volleyball,4.460279e+08,1.926386,82.277108,0.337349,0.325301,0.337349,22.090778
rowing,5.354096e+08,1.857643,81.678571,0.333333,0.333333,0.333333,23.483324
rugby sevens,5.085589e+08,1.765946,81.256757,0.337838,0.324324,0.337838,25.869383
golf,2.768164e+08,1.801667,79.166667,0.333333,0.333333,0.333333,24.296289
canoe,5.047228e+08,1.802206,78.779412,0.397059,0.397059,0.411765,24.124044
weightlifting,5.277611e+08,1.652222,78.400000,0.333333,0.333333,0.333333,27.992856
wrestling,4.728493e+08,1.725211,78.380282,0.250000,0.250000,0.500000,25.841663
judo,4.530642e+08,1.733036,77.410714,0.250000,0.250000,0.500000,25.209964
shooting,4.676571e+08,1.726829,75.707317,0.365854,0.365854,0.365854,25.317282
aquatics,4.904795e+08,1.806031,73.984436,0.463320,0.432432,0.409266,22.434049
tennis,4.462966e+08,1.797727,73.136364,0.347826,0.347826,0.347826,22.518660
athletics,5.102961e+08,1.776205,71.407186,0.379310,0.367816,0.356322,22.413280
fencing,6.077249e+08,1.789474,71.263158,0.368421,0.385965,0.385965,22.170428
cycling,5.117448e+08,1.757838,71.000000,0.360000,0.373333,0.386667,22.870379
sailing,5.421857e+08,1.770444,70.977778,0.333333,0.333333,0.333333,22.529391
hockey,5.585408e+08,1.756869,70.777778,0.343434,0.323232,0.333333,22.845683
archery,4.552117e+08,1.736000,70.500000,0.400000,0.400000,0.400000,23.211637
football,4.483902e+08,1.745463,68.711111,0.333333,0.333333,0.333333,22.354330
taekwondo,5.567125e+08,1.825000,68.419355,0.250000,0.250000,0.500000,20.434485
badminton,5.295203e+08,1.751304,67.909091,0.347826,0.347826,0.347826,22.085016
equestrian,4.498368e+08,1.750000,67.775000,0.375000,0.375000,0.375000,22.062174
modern pentathlon,5.312444e+08,1.808333,66.666667,0.333333,0.333333,0.333333,20.302707
table tennis,4.789609e+08,1.691579,61.210526,0.421053,0.421053,0.421053,21.258991
triathlon,3.841494e+08,1.745000,61.166667,0.333333,0.333333,0.333333,20.033566
gymnastics,5.249998e+08,1.633857,53.857143,0.428571,0.428571,0.428571,20.095502
boxing,4.812574e+08,1.752115,NaN,0.250000,0.250000,0.500000,NaN

5. ¿Cuál es el pais con más participación femenina?

**Respuesta 2.5**: El pais con una mayor participación femenina es **Estados unidos**.

In [6]:
# Cuál es el pais con la mayor participación femenina

athletes_medal.groupby(by =['nationality', 'sex']).sex.count().sort_values(ascending=False)

nationality  sex
USA          female    117
             male       94
GER          male       88
RUS          female     74
GBR          male       71
                      ...
NIG          male        1
PHI          female      1
POR          female      1
PUR          female      1
VIE          male        1
Name: sex, Length: 143, dtype: int64

## **Ejercicio 3 (30%)**

Importe el dataset de nba del repositorio de clase y responda (hint: Elimine las instancias con registros faltantes):

1. Cuáles son los equipos que pagan los salarios más altos (presente el resultado como un dataFrame con el nombre del equipo y la cantidad de dinero de la nómina)
2. Separe la variable *Age* en tres grupos y cree una nueva columna llamada *Age-Group* con esta información.<
3. Construya una tabla dinámica que muestre el salario promedio de los jugadores por equipo y posición para para los cinco equipos que pagan mejores salarios.